model:
  type: cnn
  conf:
    inchn: 3
    conv: [
      [16,7,7,2,2,3,3,'bn','relu','',3,3,2,2,1,1],
      [32,5,5,2,2,2,2,'bn','relu','',3,3,2,2,1,1],
      [32,5,5,2,2,2,2,'bn','relu','',3,3,2,2,1,1],
      [64,3,3,2,2,1,1,'bn','relu','',3,3,2,2,1,1],
      [128,3,3,2,2,1,1,'bn','relu','',3,3,2,2,1,1]
    ]
    dense: [
      [16, 'relu'],
      [2, '']
    ]

dataset:
  img_size: 256
  crop_size: 224
  img_affixs: [png,jpg,jpeg]
  use_CLAHE: True
  
trainer:
  model_affix: CNN5x
  optim_affix: Adam
  optim: Adam
  lr: 0.001
  scheduler: plateau
  schd_params:
    factor: 0.1
  batch_size: 64
  start_epoch: 0
  n_epochs: 60
  n_workers: 8
  log_interval: 100
  save_interval: 10
